Repository arjuncvinod/Hello-World-in-Different-Languages, pull requests merged in 2023-10, with the labels that each got.

#42 used namespace to call cout
  C++.cpp
Labels: waiting

#44 Create simple-linear-regression-in-python.py
  Programs in different languages/simple-linear-regression-in-python.py
Labels: waiting

#47 Create add number.py
  Programs in different languages/hello world.py
Labels: waiting

#53 Fixed PHP
  PHP.php
Labels: waiting

#54 Added Rock Paper Scissor game in python
  Programs in different languages/RPS.py
Labels: waiting

#57 Added Binary Search Algorithm in Python
  Programs in different languages/binarysearch.py
Labels: waiting

#59 Create Rust.rs
  Rust.rs
Labels: waiting

#67 Create CSS.css
  CSS.css
Labels: waiting

#75 Ada.ads
  Ada.ads
Labels: hacktoberfest-accepted

#77 Xml.xml: Add Hello World in XML
  Xml.xml
Labels: hacktoberfest-accepted

#78 Fix/Go.go
  Go.go
Labels: hacktoberfest-accepted

#79 Added hello world in groovy and julia language
  Groovy.groovy
  Julia.jl
Labels: waiting

#73 SML(Standard ML).sml
  SML.sml
Labels: hacktoberfest-accepted

#49 Added Majority Element Code In Java
  Programs in different languages/Majority Element.java
Labels: hacktoberfest-accepted

#52 Create ocaml.ml
  ocaml.ml
Labels: hacktoberfest-accepted

#93 Added Hello World in AppleScript
  AppleScript.applescript
Labels: hacktoberfest-accepted

#99 Hello World java
  Programs in different languages/HelloWorldJava_harsh032.java
Labels: hacktoberfest-accepted

#112 Java file updated - Spelling mistakes corrected - Removed unecessary imports
  Java.java
Labels: hacktoberfest-accepted

#120 elixir
  Elixir.ex
Labels: hacktoberfest-accepted

#129 uploaded a 6502 assembly hello world
  6503assembly.s
Labels: hacktoberfest-accepted

#134 hello world in lolocode
  lolocode.lol
Labels: hacktoberfest-accepted

#131 Malbogle
  Malbogle.malbogle
  chef.chef
Labels: hacktoberfest-accepted, Re-submit
